### ISSUE TITLE
where is the HGT?

### ISSUE THREAD

**Issue by liongliong** [krystalan/AwesomeSEG#1]
在main.py代码执行的过程中需要HGT模块，但是好像没有提供吗

**Comment by sujiaqi-1** [comment]
> 在main.py代码执行的过程中需要HGT模块，但是好像没有提供吗

I have meet the same problem,do you slove the problem?

**Comment by krystalan** [comment]
> 

HGT的代码请参考https://github.com/pyg-team/pytorch_geometric/blob/master/examples/hetero/hgt_dblp.py#L17
